<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Test"
           tests="2"
           failures="2"
           errors="0"
           skipped="0"
           time="1.430">
  <properties />
            <testcase name="testTypeShorting" time="1.032" classname="com.inquiry.tests.reportTest">
                <failure type="java.lang.AssertionError"
                  message="The following asserts failed:
	fail,
	fail,
	fail"
              >
<![CDATA[java.lang.AssertionError: The following asserts failed:
	fail,
	fail,
	fail
  org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
  com.inquiry.tests.reportTest.testTypeShorting(reportTest.java:72)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:648)
  org.testng.TestRunner.run(TestRunner.java:505)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
  org.testng.SuiteRunner.run(SuiteRunner.java:364)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
  org.testng.TestNG.runSuites(TestNG.java:1049)
  org.testng.TestNG.run(TestNG.java:1017)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
      </failure>

          </testcase>
            <testcase name="testActiveStatus" time="0.398" classname="com.inquiry.tests.reportTest">
                <failure type="java.lang.AssertionError"
                  message="The following asserts failed:
	Status did not match at reocord number -1 expected [Active] but found [ACTIVE],
	Status did not match at reocord number -2 expected [Active] but found [ACTIVE],
	Status did not match at reocord number -3 expected [Active] but found [ACTIVE],
	Status did not match at reocord number -4 expected [Active] but found [ACTIVE]"
              >
<![CDATA[java.lang.AssertionError: The following asserts failed:
	Status did not match at reocord number -1 expected [Active] but found [ACTIVE],
	Status did not match at reocord number -2 expected [Active] but found [ACTIVE],
	Status did not match at reocord number -3 expected [Active] but found [ACTIVE],
	Status did not match at reocord number -4 expected [Active] but found [ACTIVE]
  org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
  com.inquiry.tests.reportTest.testActiveStatus(reportTest.java:28)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:648)
  org.testng.TestRunner.run(TestRunner.java:505)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
  org.testng.SuiteRunner.run(SuiteRunner.java:364)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
  org.testng.TestNG.runSuites(TestNG.java:1049)
  org.testng.TestNG.run(TestNG.java:1017)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
